package hu.mktiti;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.logging.Log;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;

import java.io.*;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

@Mojo(name = "generate", defaultPhase = LifecyclePhase.GENERATE_SOURCES)
public class ConstGeneratorMojo extends AbstractMojo {

    enum Type {
        java(JavaPrinter::new),
        kotlin(KotlinPrinter::new);

        private final ConstPrinter.Factory factory;

        Type(final ConstPrinter.Factory factory) {
            this.factory = factory;
        }

        ConstPrinter getPrinter(final PrinterConf conf) {
            return factory.apply(conf);
        }
    }

    @Parameter(defaultValue = "${project.build.directory}/src/main", property = "outputDir", required = true)
    private File outputDirectory;

    @Parameter(defaultValue = "java", property = "type", required = true)
    private Type type;

    @Parameter(property = "package", required = true)
    private String packageName;

    @Parameter(property = "classname", defaultValue = "ProjectInfo")
    private String className;

    @Parameter(property = "visibility", defaultValue = "PUBLIC")
    private PrinterConf.Visibility visibility;

    @Parameter(property = "useGetters", defaultValue = "false")
    private boolean useGetters;

    @Parameter(property = "values")
    private Map<String, String> values;

    @Parameter(property = "addVersion", defaultValue = "true")
    private boolean addVersion;

    @Parameter(property = "version", defaultValue = "${project.version}")
    private String version;

    public ConstGeneratorMojo() { }

    public void execute() throws MojoExecutionException {
        final Log log = getLog();

        final PrinterConf conf = new PrinterConf(
                packageName,
                className,
                "Generated by const-generator-maven-plugin at " + LocalDateTime.now(),
                visibility,
                useGetters
        );
        final ConstPrinter printer = type.getPrinter(conf);

        final Map<String, String> variables = new HashMap<>();
        if (addVersion) {
            variables.put("version", version);
        }
        for (Map.Entry<String, String> entry : values.entrySet()) {
            if (printer.isValid(entry.getKey())) {
                final String value = (entry.getValue() == null) ? "" : entry.getValue();
                variables.put(entry.getKey(), value);
            } else {
                throw new MojoExecutionException("Value name '" + entry.getKey() + "' is not a valid identifier for type '" + type + "'");
            }
        }

        log.info("Values to add:");
        for (Map.Entry<String, String> value : variables.entrySet()) {
            log.info("    " + value.getKey() + " = " + Util.escapeString(value.getValue()));
        }

        final File genDir = Paths.get(outputDirectory.getAbsolutePath(), printer.getDirPath()).toFile();
        if (!genDir.exists() && !genDir.mkdirs()) {
            throw new MojoExecutionException("Target directory doesn't exist");
        }

        final File constFile = new File(genDir, printer.getFilename());
        log.info("Creating constant file at " + constFile.getPath());

        try (final PrintWriter writer = new PrintWriter(new FileOutputStream(constFile))) {
            printer.print(variables, writer);
        } catch (final FileNotFoundException fnfe) {
            throw new MojoExecutionException("Output file cannot be accessed");
        }

        log.info("Const file created!");
    }
}
